# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy Python app to Azure Web App: vmagelocicdtest'

on:
  push:
    branches:
    - working
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    
    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.10'
    
    - name: 'Deploy to Azure Web App'
    - uses: azure/webapps-deploy@v2
      with: 
        app-name: 'vmagelocicdtest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2095fcde665d4f1e8e98c98cb3a577c0 }}
